export const CARS_LOADING = "CARS_LOADING";
export const CARS_SUCCESS = "CARS_SUCCESS";
export const CARS_FAILURE = "CARS_FAILURE";

export const SINGLE_CARS_LOADING = "SINGLE_CARS_LOADING";
export const SINGLE_CARS_SUCCESS = "SINGLE_CARS_SUCCESS";
export const SINGLE_CARS_FAILURE = "SINGLE_CARS_FAILURE";
